---
title: "Case Study"
output: html_document
date: "2024-07-26"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Economic prosperity gives rise to significant lifestyle changes, allowing for the prioritisation of careers and education over family formation. Both the UK and Japan, as high-income countries have lower mortality and birth rates due to factors such as increased educational and career opportunities for women, higher living costs and wide-spread access to healthcare and family planning. While these trends reflect advancements in socio-economic conditions and medical access, they are also indicative of the challenges of population ageing.

**Japan** has the highest proportion of elderly citizens in the world, with over 28% of its population aged 65 and older. This demographic shift is due to Japan's sub-replacement fertility rate and decreased mortality rates.

**The UK** also is experiencing an ageing population, with around 18% if its population aged 65 and older. The UK also has a sub-replacement fertility rate and mortality rates have similarly decreased over time.

**Sub-Replacement Fertility Rate**

The number of births is lower than the number necessary to maintain population size -- this is attributed to many socio-economic factors.

In Japan, Increased cost of living has disincentivised having children as expenses related to housing and education are substantial. There is also a cultural expectation to have children only after marriage which incurs another set of costs -- this is reflected in the fact that only 2.2% of Japanese children are born outside of marriage. Furthermore, the poor work-life balance as a result of long working hours and overtime expectations leaves very little time for family life.

In the UK, childcare costs are prohibitively high -- this in conjunction with higher educational attainment and career ambition have led to the prioritisation of professional growth over childbearing.

**Decreased Mortality Rates**

Japan's mortality rates have decreased due to advancements in the medical field with vaccine rollouts and excellent health education. The healthcare system places a strong emphasis on preventative care, leading to early detection and treatment of illness. Additionally, there is a cultural belief in civic responsibility regarding health, which promotes better diets and adoption of active lifestyles.

In the UK, improved living conditions and education -- combined with widespread access to healthcare services have led to a rapid decline in mortality rate.

(pop pyramid of jp)

A population pyramid illustrating Japan's demographic shift clearly shows this transition towards an ageing population. (figure title and figure legend)

(pop pyramid of uk)

Despite these similar demographic shifts, the quality of life for elderly populations in the UK and Japan varies significantly -- specifically in the management of non-communicable disease (NCD). As seen below (include ncd graphs)

**What are Non-Communicable Diseases?**

Non-communicable diseases, known more commonly as chronic diseases are the leading cause of death globally. Examples include heart disease, cancer, chronic respiratory disease and diabetes -- their chronic nature requires ongoing medical care, and management. The risk of developing NCDs increases with age, consequently leading to high prevalence amongst older adults.

**What is the significance of NCDs in healthcare?**

[Increased Vulnerability]{.underline}

Non-communicable diseases pose significant challenges to healthcare systems due to the increased vulnerability of affected individuals, especially during pandemics. Evidence indicates that NCDs increase the likelihood of hospitalisation or death from COVID-19, highlighting the increased vulnerability of individuals with NCDs and the consequent strain on health services. This exemplifies the risk posed by these conditions, in regards to individual health and to the stability of healthcare systems.

[Multimorbidity and its Complications]{.underline}

Individuals with NCDs can also suffer from multiple chronic conditions simultaneously, which is referred to as multimorbidity. They may experience chronic pain, poor mental wellbeing and impairment of daily living -- affecting their independence.

Managing NCDs incurs significant healthcare costs, including expenses related to medication, rehabilitation and long-term care as these conditions often require lifelong management which results in continuous healthcare expenditure. There are also personal losses as a result that can impact people on an individual level, absences and poor productivity as a result of illness may impact income and result in financial stress.
